# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x13legacy.inventory.v1\x1a\x1cgoogle/api/annotations.proto\"W\n\x04Item\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07on_hand\x18\x03 \x01(\x05\x12\x10\n\x08reserved\x18\x04 \x01(\x05\x12\x11\n\twarehouse\x18\x05 \x01(\t\"\x1d\n\x0eGetItemRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\"8\n\x10ListItemsRequest\x12\x11\n\twarehouse\x18\x01 \x01(\t\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"L\n\x11ListItemsResponse\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.legacy.inventory.v1.Item\x12\r\n\x05total\x18\x02 \x01(\x05\"F\n\x13ReserveStockRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x10\n\x08order_id\x18\x03 \x01(\t\"R\n\x14ReserveStockResponse\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08reserved\x18\x02 \x01(\x05\x12\n\n\x02ok\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t2\xe8\x02\n\tInventory\x12\x62\n\x07GetItem\x12#.legacy.inventory.v1.GetItemRequest\x1a\x19.legacy.inventory.v1.Item\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/items/{sku}\x12m\n\tListItems\x12%.legacy.inventory.v1.ListItemsRequest\x1a&.legacy.inventory.v1.ListItemsResponse\"\x11\x82\xd3\xe4\x93\x02\x0b\x12\t/v1/items\x12\x87\x01\n\x0cReserveStock\x12(.legacy.inventory.v1.ReserveStockRequest\x1a).legacy.inventory.v1.ReserveStockResponse\"\"\x82\xd3\xe4\x93\x02\x1c\"\x17/v1/items/{sku}:reserve:\x01*b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INVENTORY'].methods_by_name['GetItem']._loaded_options = None
  _globals['_INVENTORY'].methods_by_name['GetItem']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/items/{sku}'
  _globals['_INVENTORY'].methods_by_name['ListItems']._loaded_options = None
  _globals['_INVENTORY'].methods_by_name['ListItems']._serialized_options = b'\202\323\344\223\002\013\022\t/v1/items'
  _globals['_INVENTORY'].methods_by_name['ReserveStock']._loaded_options = None
  _globals['_INVENTORY'].methods_by_name['ReserveStock']._serialized_options = b'\202\323\344\223\002\034\"\027/v1/items/{sku}:reserve:\001*'
  _globals['_ITEM']._serialized_start=70
  _globals['_ITEM']._serialized_end=157
  _globals['_GETITEMREQUEST']._serialized_start=159
  _globals['_GETITEMREQUEST']._serialized_end=188
  _globals['_LISTITEMSREQUEST']._serialized_start=190
  _globals['_LISTITEMSREQUEST']._serialized_end=246
  _globals['_LISTITEMSRESPONSE']._serialized_start=248
  _globals['_LISTITEMSRESPONSE']._serialized_end=324
  _globals['_RESERVESTOCKREQUEST']._serialized_start=326
  _globals['_RESERVESTOCKREQUEST']._serialized_end=396
  _globals['_RESERVESTOCKRESPONSE']._serialized_start=398
  _globals['_RESERVESTOCKRESPONSE']._serialized_end=480
  _globals['_INVENTORY']._serialized_start=483
  _globals['_INVENTORY']._serialized_end=843
# @@protoc_insertion_point(module_scope)
